#
# Build nextcloud docker images
#
image: atlassian/default-image:2

pipelines:
  default:
    - step:
        size: 2x
        services:
          - docker
        script: 
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          - export "IMAGE_NAME=bleed2002/nextcloud"

          # Build nextcloud v13
          #- docker build -f Dockerfile.13.0 -t "$IMAGE_NAME:v13" .
          #- docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
          #- docker push "$IMAGE_NAME:v13"

          # Build nextcloud v14
          #- docker build -f Dockerfile.14.0 -t "$IMAGE_NAME:v14" .
          #- docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
          #- docker push "$IMAGE_NAME:v14"
          
          # Build nextcloud v15
          #- docker build -f Dockerfile.15.0 -t "$IMAGE_NAME:v15" .
          #- docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
          #- docker push "$IMAGE_NAME:v15"

          # Build nextcloud v16
          #- docker build -f Dockerfile.16.0 -t "$IMAGE_NAME:v16" .
          #- docker tag "$IMAGE_NAME:v16" "$IMAGE_NAME:latest"
          #- docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
          #- docker push "$IMAGE_NAME:v16"

          # Build nextcloud v17
          - docker build -f Dockerfile.17.0 -t "$IMAGE_NAME:v17" .
          - docker tag "$IMAGE_NAME:v17" "$IMAGE_NAME:latest"
          - docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
          - docker push "$IMAGE_NAME:v17"
