name: Docker Build and Push

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: bleed2002/nextcloud

jobs:
    docker_build_push:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: "Setup: docker buildx"
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            # Build docker image
            - name: "Docker: Build and push (NC v22)"
              uses: docker/build-push-action@v2
              with:
                  file: Dockerfile.ng-v22
                  push: true
                  tags: |
                      bleed2002/nextcloud:ng-v22

            # Build docker image
            - name: "Docker: Build and push (NC v23)"
              uses: docker/build-push-action@v2
              with:
                  file: Dockerfile.ng-v23
                  push: true
                  tags: |
                      bleed2002/nextcloud:ng-v23
                      bleed2002/nextcloud:ng-latest
