name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: bleed2002/nextcloud

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build nextcloud v20
      - name: Build nextcloud v20 image
        run: |
          docker build -f Dockerfile.20.0 -t "$IMAGE_NAME:v20" .
          docker tag "$IMAGE_NAME:v20" "$IMAGE_NAME:latest"
          docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker push "$IMAGE_NAME:v20"
